### ISSUE TITLE
Flink on DCOS 1.7 

### ISSUE THREAD

**Issue by Igosuki** [mesosphere/dcos-flink-service#21]
Hello guys, I managed to build flink-mesos against mesos 0.28.1, deploy it on DCOS 1.7 and run WordCount.jar, I know 1.7 is now kind of a legacy version but in case you need it I got it up and running.

**Comment by Makman2** [comment]
Feel free to submit a PR with your files (doesn't have to be perfectly clean, just bunch in all your files ;D). I'm currently not involved any more, maybe @joerg84 is willing to look at it 👍

**Comment by EronWright** [comment]
I don't think Flink truly works on Mesos 0.28 because it relies on a feature of the fetcher (the ability to fetch files to a subdirectory of the sandbox directory).  Also Flink isn't tested on pre-1.0.   @Igosuki feel free to share a github link for posterity.
