### ISSUE TITLE
Is this the official code for the flink dcos package at https://universe.dcos.io/#/package/flink/version/latest?

### ISSUE THREAD

**Issue by asicoe** [mesosphere/dcos-flink-service#46]
Hi,

Is this the official code for the flink dcos package at https://universe.dcos.io/#/package/flink/version/latest?

If yes why is the code not reflecting the latest package version 1.3.1-1.2-1.3 ? i.e. I can't see the tag for it.

Thanks

**Comment by joerg84** [comment]
We haven't always been consistent in creating with creating tags in here (as the docker image tags are the most relevant), will make sure to improve that with the upcoming 1.4 release.

**Comment by asicoe** [comment]
Ok. So then the latest commit on master corresponds to the latest docker image tag in docker hub and dcos universe?
What about the other docker image tags? How can we trace back to the particular code commit for them?

**Comment by joerg84** [comment]
From now on there should be a correspondence between repo tags and docker image tags.

**Comment by joerg84** [comment]
@asicoe Are you trying to trace some specific version?
